name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Set up NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install Lerna
        run: npm install -g lerna

      - name: Install dependencies
        working-directory: packages/utils
        run: pnpm install

      - name: Lerna version
        working-directory: packages/utils
        run: lerna version --force-publish --exact --no-git-tag-version --no-push

      - name: Publish package
        working-directory: packages/utils
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: pnpm publish
