name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: packages/utils
        run: pnpm install

      - name: Determine release type
        id: get_commit_message
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Version package
        working-directory: packages/utils
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node ../../versioning.js "${{ steps.get_commit_message.outputs.commit_message }}"

      - name: Publish package
        working-directory: packages/utils
        run: |
          cd packages/utils
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_AUTH_TOKEN }} > ~/.npmrc
          pnpm publish --no-git-checks
          rm ~/.npmrc
